### PR TITLE
Update deprecated MATLAB functions, fix incorrect interpolation method.

### PR DESCRIPTION
**Pull request by AaronWebster**
Updates the following functions/methods as per MATLAB's code compatibility report:

> char(10) -> newline
> isdir -> isfolder
> isstr -> ischar
> hist -> histogram
> blkproc -> blockproc
> addParamValue -> addParameter

`ieRunValidateAll` and `ieRunTutorialsAll` pass except for the `v_cp` and `v_rdtScene` (previously broken).

### CODE REVIEW

**Comment by wandell** [comment]
Hi,

I looked over many of the changes - which seem fine.  I understand that you ran ieRunValidateAll and ieRunScriptsAll, and that nearly everything ran except the goofy RDT script, which should be eliminated, and the v_cp script.  

True?  In which case I will merge these many changes.

Thanks,
Brian

**Comment by AaronWebster** [comment]
Correct, ieRunValidateAll and ieRunScriptsAll all pass for me except for v_cp and v_rdtScene.  v_cp is a work in progress and v_rdtScene should be removed as you noted.

**Comment by wandell** [comment]
Thanks.  I will merge this weekend when I return from travel.


Brian Wandell
Stein Family Chair
Stanford University
Http://www.stanford.edu/~wandell
________________________________

**Comment by digital-pro** [comment]
Fixed v_cp & removed related comment in v_ISET. My bad for not catching this sooner!

**Comment by AaronWebster** [comment]
Correction, the following scripts are broken, but do not appear to be a result of this change:

isetcam\scripts\human\s_humanLineSpread.m -- BROKEN!
isetcam\scripts\human\s_humanSafetyThermal.m -- BROKEN!
isetcam\scripts\human\s_humanWavelengthDiscrimination.m -- BROKEN!
isetcam\scripts\metrics\scielab\s_scielabTutorial.m -- BROKEN!
isetcam\scripts\optics\s_opticsDLPsf.m -- BROKEN!
isetcam\scripts\sensor\s_sensorCFA.m -- BROKEN!
isetcam\scripts\sensor\s_sensorDPAFMicrolens.m -- BROKEN!

**Pull request merged**
